services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: gym_app
      POSTGRES_PASSWORD: gym_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
